global:
  tracking_url : "http://ec2-15-222-29-84.ca-central-1.compute.amazonaws.com:5000/"
  experiment_name : "dvc-pipeline-runs"
data_ingestion:
  test_size: 0.2
model_building:
  ngram_range: [1, 3]
  max_features: 1000
  learning_rate: 0.09
  max_depth: 20
  n_estimators: 367